- name: copy the sonar plugin files
  copy:
    src: files/plugins/{{ item }}
    dest: /opt/sonarqube/extensions/plugins/
  with_items:
   		- sonar-cobertura-plugin-2.0.jar
      - sonar-csharp-plugin-7.3.0.5690.jar
      - sonar-css-plugin-1.1.1.1010.jar
      - sonar-flex-plugin-2.5.1.1831.jar
      - sonar-gitlab-plugin-4.1.0-SNAPSHOT.jar
      - sonar-go-plugin-1.1.1.2000.jar.old
      - sonar-go-plugin-1.6.0.719.jar
      - sonar-html-plugin-3.0.1.1444.jar
      - sonar-java-plugin-5.6.0.15032.jar
      - sonar-javascript-plugin-5.1.1.7506.jar
      - sonar-ldap-plugin-2.2.0.608.jar
      - sonar-php-plugin-3.0.0.4537.jar
      - sonar-python-plugin-1.14.1.3143.jar
      - sonar-scm-git-plugin-1.8.0.1574.jar
      - sonar-scm-svn-plugin-1.7.0.1017.jar
      - sonar-typescript-plugin-1.9.0.3766.jar
      - sonar-xml-plugin-1.5.1.1452.jar

   
   
