- name: Install OpenJdk 11 on a Server
  hosts: server
  vars:
    - java_version: java-11-openjdk-11.0.6.10-1.el7_7.x86_64
  tasks:
   - name: Check the connectivity
     ping:
   - name: "Yum Install {{ java_version}}"
     yum:
      name: "{{ item }}"
      state: latest
     with_items:
      - "{{java_version}}" 
     become: true
     become_method: sudo
   - name: Set Environment Variable such as Java Home
     shell: "export JAVA_HOME=/usr/lib/jvm/{{java_version}}"
   - name: line insert
     lineinfile:
       path: /root/.bashrc
       line: 'export JAVA_HOME=/usr/lib/jvm/{{java_version}}'
       insertbefore: EOF
   - name: Set Default java for the System 
     shell: "alternatives --set java /usr/lib/jvm/{{java_version}}/bin/java"
     become: true
     become_method: sudo
   - debug:
        msg: "Java Version : {{java_version}} installed "
