- name: Install SonarQube sonarqube-7.9.2 LTS  on a Server
  hosts: server
  vars:
    - sonar_version: sonarqube-7.9.2
  tasks:
   - name: Check the connectivity
     ping:
   - name: Download and install the Sonar zip File
     unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/{{sonar_version}}.zip
      dest: /opt/
      remote_src: yes
   - name: Ensure group "somegroup" exists
     group:
       name: sonar
       state: present
   - name: Add the user 'sonar' with a specific uid and a primary group of 'sonar'
     user:
      name: sonar
      comment: Sonar User
      uid: 1040
      group: sonar
   - name: Change the Sonar directory owner to sonar
     file:
       path: /opt/{{sonar_version}}
       state: directory
       recurse: yes
       owner: sonar
       group: sonar
   - name: Set Environment Variable such as Sonar Home
     shell: "export SONAR_HOME=/opt/{{sonar_version}}"
   - name: line insert
     lineinfile:
       path: /root/.bashrc
       line: 'export SONAR_HOME=/opt/{{sonar_version}}'
       insertbefore: EOF
   - name: Check the verion
     shell: "env | grep SONAR_HOME"
     register: sonar_update
   - debug:
        msg: "Sonar installed at {{sonar_update.stdout}} "
