---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - initscripts
      - "{{ 'libselinux-python' if ansible_python['version']['major'] < 3 else 'python3-libselinux' }}"
    state: present

- name: Download jenkins.repo
  get_url:
   url: "{{ jenkins_repo_url }}"
   dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
   state: present
   key: "{{ jenkins_repo_key_url }}"

- name: Ensure Jenkins is installed.
  package:
    name: jenkins
    state: present
  notify: configure default users


